### ISSUE TITLE
How you deal with certificate pinning?

### ISSUE THREAD

**Issue by HasBert** [privacyint/appdata-environment-desktop#1]
First of all thank you for your work! :)
I haven't tried your setup, yet, but I'm currently playing around with mitmproxy inside a docker container. In my setup I use my Linux machine as a gateway for my smartphone, as explained [here](https://docs.mitmproxy.org/stable/howto-transparent/). While playing around I recognized, that Apps like e.g. PayPal found out, via certificate pinning, that I was intercepting the connection, while I was trying to login.
As I can remember, you're focusing on the startup sequence of an App and what it sends before the user interacts with it? Correct me, if I'm wrong.
How do you deal with pinned certificates? Is it a problem at startup? Is it a problem for your analysis?
I found [a few techniques to get around certificate pinning](https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/). Do you think this could be integrated in your project too? I mean some sort of automated App downloader and manipulator before installing the .apk on a device or an Android Virtual Device.
Please feel free to ask if you don't understand, or correct me if I'm wrong.
Cheers

**Comment by CJFWeatherhead** [comment]
Hi HasBert,

Sorry for the long delay in the response.

In our [research](https://privacyinternational.org/appdata) I didn't encounter issues with certificate pinning. In theory the Android UA should disable pinning on user installed trusts if it follows the [RFC recommendations (RFC7469 s.2.6, paragraph 2)](https://tools.ietf.org/html/rfc7469#section-2.6), however how this would be ascertained when the certificate is installed in /system I don't know, so I don't think it would apply (probably does on Android 6.x and earlier with user installed trusts). It may detect a user-trust if its in both the user store and the system store, however this is speculative as I don't know the behaviour internally inside Android.

From my experience very few apps appear to pin, and not one third party SDK's/API's tested did. If the pinning is done natively and statically, then I don't think there is any way to remove it (shy of recompiling)

Sorry to not be more helpful. If you feel this should be noted in the documentation, please make a pull request however I'm not going to make any internal changes in my environment to accommodate this, so I am closing this issue.

Regards,
Chris

**Comment by HasBert** [comment]
Hi Chris,

thank you for your reply. 
I'll check this, if I encounter bigger problems with. In my setup I install the certificate in the /system trust store, so I don't need to provide a pincode for Android 6+.

> hen I don't think there is any way to remove it (shy of recompiling)

Yeah I see your concerns there! I think it's possible with a framework like [Frida](https://koz.io/tags/frida/), but I don't know now if it's legal to repacke a .apk which I don't own.

> Sorry to not be more helpful.

You were helpful. ;) 

> I'm not going to make any internal changes in my environment

Fully understandable if you haven't encountered problems with third party SDK's/API's.

P.S. because of your talk the 35C3 I found a topic for my bachelor thesis. Thanks for that. ;)
Cheers Marvin
