### ISSUE TITLE
.OVA link down

### ISSUE THREAD

**Issue by BenjaminPoilve** [privacyint/appdata-environment-desktop#14]
Hello, 
I am trying to use your interception environnement but it seems like the link for your .ova is down. The one I found is: https://media.privacyinternational.org/infrastructure/virtual-machines/Privacy-International-data-interception-environment-stable-2.1.2.ova 

One thing you could do is publish it on Github as a release to have an alternative way of downloading it!

Thanks for your work!

**Comment by BenjaminPoilve** [comment]
I had a copy on an old laptop, I took the liberty to set up a mirror: https://github.com/BenjaminPoilve/PrivacyIntVMMirror/releases

**Comment by CJFWeatherhead** [comment]
Thanks, original link should be working again too!
