### ISSUE TITLE
Why do you use --showhost?

### ISSUE THREAD

**Issue by rkba** [privacyint/appdata-environment-desktop#16]
Why do you use `--showhost`?

Why is this useful?
(I still don't get the mitmproxy doc to see the difference what it uses if this option is not present – the HTTP request URL, I guess?)

https://github.com/privacyint/appdata-environment-desktop/blob/10fd6bdf564a7eebbac2d1a8e117fa644daec02b/mitmproxy_start.sh#L2

**Comment by CJFWeatherhead** [comment]
I use showhost to show the full DNS names of resources, otherwise, if I recall correctly, mitmproxy only shows the IP address

**Comment by rkba** [comment]
Ok. AFAIK mitmweb always seems to show the host, only mitmproxy shows the IP otherwise.
Anyway, thanks for the reply.
