### ISSUE TITLE
Virtual Machine doesn't run

### ISSUE THREAD

**Issue by dragonxtek** [privacyint/appdata-environment-desktop#8]
I'm using VirtualBox 5.2.18 under Ubuntu 18.10 and after grub screen, the screen remains black with two small white lines and does not start.

![Privacy Internationals data interception environment  Running  - Oracle VM VirtualBox_595](https://user-images.githubusercontent.com/10552658/61129214-e880c380-a481-11e9-9606-5bd01122206a.png)

**Comment by CJFWeatherhead** [comment]
I'm sorry, the environment has only been run in VirtualBox 6.x, I don't know of its compatibility in 5.x and earlier. 5.2.18 is EOL (5.2.30 being the latest 5.x branch), so I won't be fixing this.

**Comment by dragonxtek** [comment]
I tested on version 6.0.8 and now it works. Thanks
